apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.releaseName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600  # Timeout for the job execution in seconds (10 minutes)
      template:
        spec:
          containers:
          - name: {{ .Values.releaseName }}
            image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          restartPolicy: OnFailure
