apiVersion: batch/v1
kind: Job
metadata:
  name: create-pvc-job
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      containers:
      - name: create-pvc
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          if ! kubectl get pvc {{ .Values.persistentVolumeClaim.name }} --namespace={{ .Values.namespace }} > /dev/null 2>&1; then
            echo "PVC does not exist. Creating PVC..."
            kubectl apply -f /pvc-definition.yaml
          else
            echo "PVC already exists. Skipping creation."
          fi
      restartPolicy: OnFailure
