releaseName: cronjob-v4

namespace: cronjob-v4
schedule: "*/10 * * * *"
image:
  repository: prasoonshrama25/k8s-deployment-dockerimage
  tag: "latest"
outputPath: "logs/version2"
persistentVolumeClaim:
  name: cronjob-app-pvc

