releaseName: cronjob-v2
namespace: cronjob-v2
schedule: "*/10 * * * *"
image:
  repository: prasoonshrama25/k8s-deployment-dockerimage
  tag: "latest"
outputPath: "logs/version2"
createPersistentVolumeClaim: true  # Set to false to skip PVC creation
persistentVolumeClaim:
  name: cronjob-app-pvc
storageClassName: standard
